FROM ubuntu:22.04
RUN apt update && apt install -y build-essential cmake libboost-all-dev libssl-dev nlohmann-json3-dev libspdlog-dev libsodium-dev protobuf-compiler
COPY . /app
WORKDIR /app
RUN mkdir build && cd build && cmake .. -DBUILD_NODE=ON && make -j4
CMD ["./build/src/mesh-node"]