version: '3'
services:
  server:
    build:
      context: ./meshcompute-cpp
      dockerfile: docker/Dockerfile.server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./meshcompute-cpp/config/config.json:/etc/meshcompute/config.json
      - ./meshcompute-cpp/certs:/etc/meshcompute/certs
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
  controller:
    build:
      context: ..
      dockerfile: docker/Dockerfile.controller
    stdin_open: true
    tty: true
    depends_on:
      - server
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bot
    deploy:
      replicas: 2
    depends_on:
      - server